CREATE TABLE IF NOT EXISTS spieler (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    passwort_hash TEXT NOT NULL,
    erstellt_am TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS spieler_ressourcen (
    id SERIAL PRIMARY KEY,
    spieler_id INTEGER NOT NULL UNIQUE REFERENCES spieler(id) ON DELETE CASCADE,
    geld BIGINT NOT NULL DEFAULT 500000,
    stein BIGINT NOT NULL DEFAULT 500,
    eisen BIGINT NOT NULL DEFAULT 200,
    strom BIGINT NOT NULL DEFAULT 100,
    treibstoff BIGINT NOT NULL DEFAULT 50
);